language: bash
before_script:
  - go get github.com/sijad/yaml-translation-utils/same-yaml
  - go get github.com/sijad/yaml-translation-utils/yamllinter
script:
  - bash scripts/identical.sh
  - bash scripts/linter.sh
